<a href="https://colab.research.google.com/github/manu310patel/NPTEL-ML/blob/main/Introduction_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Playing around colab environment

In [ ]:
!lscpu|grep 'Model name'

In [ ]:
!lscpu|grep 'Core(s) per socket:'

In [ ]:
!lscpu|grep 'Thread(s) per core'

In [ ]:
!free -mh

In [ ]:
!df -h

In [ ]:
!pwd

In [ ]:
!ls -l

In [ ]:
!mkdir my_dir

In [ ]:
!ls

In [ ]:
%cd my_dir

In [ ]:
!pwd

Check the python version

In [ ]:
!python --version

## Basic Datatypes

### Numbers

In [ ]:
x = 1

In [ ]:
x

In [ ]:
print(x)

In [ ]:
type(x)

In [ ]:
y = 1.0

In [ ]:
type(y)

In [ ]:
y

In [ ]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

In [ ]:
x += 1 # x = x + 1
print(x)
x *= 2 # x = x * 2
print(x)

In [ ]:
x = 5
print(x/2)
print(x//2)

### Boolean

In [ ]:
x = True

In [ ]:
x

In [ ]:
type(x)

In [ ]:
y = False

In [ ]:
print(x and y) # Logical AND;
print(x or y)  # Logical OR;
print(not x)   # Logical NOT;
print(x != y)  # Logical XOR;

### String

In [ ]:
x = 'hello world' # "hello world"

In [ ]:
x

In [ ]:
type(x)

In [ ]:
y = "hello world"

In [ ]:
y

In [ ]:
len(y)

In [ ]:
print('He said, "Hello World!"')

In [ ]:
print("He said, 'Hello World!'")

In [ ]:
s = 'Hello ' + 'world!'

In [ ]:
s

For more on python data types, refer to [this doc](https://www.w3schools.com/python/python_datatypes.asp). Some additional data types are defined in numpy
library ([link](https://numpy.org/doc/stable/user/basics.types.html)).

## Containers

### List

In [ ]:
a = [1, 2, 3, 4, 5]

In [ ]:
a

In [ ]:
type(a)

In [ ]:
len(a)

In [ ]:
a[0]

In [ ]:
a[1]

In [ ]:
a[-1] # equivalent to a[len(a)+i]

In [ ]:
a[-2]

List Slicing

In [ ]:
a[0:3] # [a[0], a[1], a[2]]

In [ ]:
a[1:2] # [a[1]]

In [ ]:
a[:2] # [a[0], a[1]]

In [ ]:
a[0:-1] # [a[0], a[1], a[2], a[3]]

In [ ]:
a[1:] # [a[1], a[2], a[3], a[4]]

You can create list of heterogeneous items

In [ ]:
a = [1, 2.0, 'three']

In [ ]:
a

A list can contain another list as an element

In [ ]:
a = [1, 2, [3, 4]]

In [ ]:
a[2]

Some operations on List

In [ ]:
[1, 2] + [3, 4]

In [ ]:
sum([0, 1, 2, 3])

In [ ]:
l = [0, 1, 2, 3]
l.reverse()
print(l)

In [ ]:
l = [3, 1, 7, 2, 5]
l.sort()
print(l)

Also look for python <em>tuples</em> and how it is different from python <em>list</em>.

### Dictionaries

In [ ]:
d1 = {'key1': 'value1', 'key2': 2, 'key3': 3.0}

In [ ]:
print(d1['key1'])
print(d1['key2'])
print(d1['key3'])

In [ ]:
d2 = {}
d2[1] = 'v1'
d2[2] = 'v2'
d2[3] = 'v3'

In [ ]:
print(d2[1])
print(d2[2])
print(d2[3])

In [ ]:
print(list(d2.keys()))

In [ ]:
print(list(d2.values()))

In [ ]:
for k, v in d2.items():
  print('key: %s\tvalue: %s'%(k, v))

In [ ]:
nums = [0, 1, 2, 3, 4]
num_to_square = {x: x ** 2 for x in nums}
print(num_to_square)

Also look into python <em>sets</em>.

## Loop

In [ ]:
for i in [0, 1, 2, 3, 4]:
  print(i)

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for i in nums:
  squares.append(i ** 2)

In [ ]:
squares

In [ ]:
squares_new = [e ** 2 for e in nums]

In [ ]:
squares_new

In [ ]:
even_squares = [e ** 2 for e in nums if e % 2 == 0]

In [ ]:
even_squares

You can also use [while loop](https://www.w3schools.com/python/python_while_loops.asp) in python.

## Functions

In [ ]:
def fabs(num):
  if num >= 0:
    return num
  else:
    return -num

In [ ]:
print(fabs(5))
print(fabs(-5))

You can also define python function within another function

In [ ]:
def square_sum(nums):
  def square(x):
    return x ** 2
  return sum([square(e) for e in nums])

In [ ]:
print(square_sum([0, 1, 2, 3, 4]))

You can refer to [this doc](https://www.w3schools.com/python/python_functions.asp) to learn more about python <em>function</em>. Also, look for python <em>lambda</em> functions([link](https://www.w3schools.com/python/python_lambda.asp)).

Python also support object-oriented programming. You can look for python <em>classes</em>.

# Python modules

In [ ]:
import math

In [ ]:
math.ceil(0.5)

In [ ]:
math.floor(0.5)

In [ ]:
math.fabs(-0.5)

In [ ]:
import math as m

In [ ]:
m.fabs(-0.5)

Sometimes python modules are group together in different packages. Some packages may not be installed in your system by default. If a python package is not already installed in your system, it need to be installed before using it. Please refer to [this tutorial](https://packaging.python.org/en/latest/tutorials/installing-packages/) to know how to install python packages.

You can use the following command to list all the python packages installed in Colab

In [ ]:
!pip list -v 

# Numpy

Numpy is a python library which provides access to high perfomance arrays. For the detailed functionalites of Numpy, please refer to [this tutorial](https://www.w3schools.com/python/numpy/default.asp)

In [ ]:
import numpy as np

In [ ]:
a = np.array([0, 1, 2, 3])

In [ ]:
print(a)

In [ ]:
type(a)

In [ ]:
a.shape

In [ ]:
a.dtype

In [ ]:
a = np.array([0, 1, 2, 3], dtype=np.float32)

In [ ]:
print(a)

In [ ]:
a.dtype

In [ ]:
a[1]

In [ ]:
a[-2]

In [ ]:
# Creating 2-D array
# [[1, 2, 3],
#  [4, 5, 6]]
a = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
print(a)

In [ ]:
a.shape

In [ ]:
a[1, 2]

In [ ]:
a[0, -1]

In [ ]:
a[1]

### Creating some special array

In [ ]:
z = np.zeros((3, 4)) # Create an array of all zeros

In [ ]:
z

In [ ]:
z.dtype

In [ ]:
o = np.ones((2, 3), dtype=np.int16) # Create an array of all ones

In [ ]:
o

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

### Array slicing

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

### Row-wise and column-wise accessing

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

### Array math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

### vector-vector inner product, matrix-vector multiplication and matrix-matrix multiplication

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

In [ ]:
print(v @ w)

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

### Some utility functons for arrays

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v)
print("transpose\n", v.T)

You can refer to [this tutorial](https://colab.research.google.com/github/cs231n/cs231n.github.io/blob/master/python-colab.ipynb) for a more detailed introduction to python with google colab.